spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PASSWORD}


token:
  secret:
    key: ${TOKEN_SECRET_KEY}
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12
