server:
  port: 8081


spring:
  application:
    name: store-admin

  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PASSWORD}